[server]
name = "Hackthon Document Mcp Server"
version = "1.0.0"
description = "MCPハッカソンのドキュメントサーバ"
author = "Masato Asai"

[transport]
default = "stdio"
http_port = 8000
http_host = "127.0.0.1"

[features]
enable_logging = true
log_level = "INFO"
enable_metrics = false 
