[server]
name = "Hello World Server"
version = "1.0.0"
description = "初学者向けのMCPサーバーサンプル"
author = "あなたの名前"

[transport]
default = "stdio"
http_port = 8000
http_host = "127.0.0.1"

[features]
enable_logging = true
log_level = "INFO"
enable_metrics = false 